name: takutore
description: A new Flutter application.
publish_to: 'none'
version: 1.3.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  firebase_messaging: ^7.0.0
  firebase_remote_config: ^0.3.0+3
  google_sign_in: ^4.5.1
  apple_sign_in: ^0.1.0
  flutter_facebook_login: ^3.0.0
  # View
  cupertino_icons: ^0.1.3
  flutter_app_badger: ^1.1.2
  flutter_rating_bar: ^3.0.1+1
  flutter_slidable: ^0.5.5
  # Helper
  algolia: ^0.1.7
  image_picker: ^0.6.7+1
  image_cropper: ^1.2.3
  timeago: ^2.0.26
  http: ^0.12.2
  url_launcher: ^5.5.0
  # State
  provider: ^4.1.2
  # Environment
  flutter_dotenv: ^2.1.0
  package_info: ^0.4.3
  version: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: true
  ios: true
  image_path: images/app_icon.png

flutter_native_splash:
  image: images/splash_icon.png
  color: "ffffff"

flutter:
  uses-material-design: true
  assets:
    - .env
    - images/google.png
    - images/apple.png
    - images/facebook.png
    - images/fitness.png
    - images/algolia.png
