name: takutore
description: A new Flutter application.
publish_to: 'none'
version: 1.3.0+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase
  firebase_core: ^1.7.0
  firebase_analytics: ^8.3.3
  firebase_auth: ^3.1.3
  cloud_firestore: ^2.5.3
  firebase_storage: ^10.0.5
  firebase_messaging: ^10.0.8
  firebase_remote_config: ^0.11.0+1
  google_sign_in: ^5.1.1
  sign_in_with_apple: ^3.2.0
  flutter_login_facebook: ^1.1.0
  nonce: ^1.2.0
  crypto: ^3.0.1
  # View
  cupertino_icons: ^1.0.3
  flutter_app_badger: ^1.3.0
  flutter_rating_bar: ^4.0.0
  flutter_slidable: ^0.6.0
  # Helper
  algolia: ^1.0.1
  image_picker: ^0.8.4+2
  image_cropper: ^1.4.1
  timeago: ^3.1.0
  http: ^0.13.4
  url_launcher: ^6.0.12
  # State
  provider: ^6.0.1
  # Environment
  package_info_plus: ^1.3.0
  version: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4

flutter_icons:
  android: true
  ios: true
  image_path: images/app_icon.png

flutter_native_splash:
  image: images/splash_icon.png
  color: "ffffff"

flutter:
  uses-material-design: true
  assets:
    - images/google.png
    - images/apple.png
    - images/facebook.png
    - images/fitness.png
    - images/algolia.png
